### ISSUE TITLE
Newline at the end of output

### ISSUE THREAD

**Issue by kolloch** [stoeffel/nix-test-runner#2]
I'd prefer if `nix-test` had a newline after the last test results.

```bash
$ nix-test ./crate2nix/templates/nix/crate2nix/tests/default.nix; echo "<<<<ECHO AFTER TEST>>>"

    
    TEST RUN PASSED

    Duration: 98 ms
    Passed:   29 
    Failed:   0 
                                    <<<<ECHO AFTER TEST>>>
```

Thanks for providing this! I had a crude test runner included in my [crate2nix](https://github.com/kolloch/crate2nix) rust tests before but not the output in the error case is so much nicer.

**Comment by stoeffel** [comment]
closed with [0.4.3](https://crates.io/crates/nix-test-runner/0.4.3). thanks for reporting this!
