### ISSUE TITLE
Support for running nix-test-runner from nix

### ISSUE THREAD

**Issue by kolloch** [stoeffel/nix-test-runner#3]
I am not sure if you already thought about it but it would be awesome to run the tests inside of a derivation.

* Building nix-test-runner within nix with one crate per derivation is relatively easy: See https://github.com/kolloch/crate2nix/blob/master/nix/nix-test-runner.nix
* It would be nice to have some utility (nix) methods in nix-test-runner like e.g.:
   ```nix
   let nixTest = pkgs.callPackage ...;
   in nixTest.run { tests = ./tests.nix; }
   ```
* We would probably either have to set up different store paths or [use recursive nix](https://github.com/NixOS/nix/pull/3205).

I use nix-test-runner for unit tests only, so it would be even OK if storing derivation etc would be disabled.

What do you think?

**Comment by stoeffel** [comment]
I haven't thought about that yet. I'm totally open to this, but I don't think that I'll get to it soon. Therefore, I  would appreciate a PR :-)
